# Generated by Django 6.0.6 on 2026-06-12 17:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=32)),
                ('new_status', models.CharField(blank=True, max_length=32)),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('event_type', models.CharField(choices=[('availability_changed', 'Availability changed'), ('price_changed', 'Price changed'), ('found', 'Found'), ('disappeared', 'Disappeared')], max_length=32)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-detected_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='PLN', max_length=8)),
                ('availability', models.CharField(choices=[('unknown', 'Unknown'), ('missing', 'Missing'), ('out_of_stock', 'Out of stock'), ('in_stock', 'In stock'), ('preorder', 'Preorder')], default='unknown', max_length=32)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField()),
                ('parser_type', models.CharField(choices=[('generic', 'Generic')], default='generic', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_seconds', models.PositiveIntegerField(default=5)),
                ('timeout_seconds', models.PositiveIntegerField(default=15)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('discord', 'Discord'), ('email', 'Email')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('destination', models.CharField(blank=True, max_length=500)),
                ('payload_summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='monitor.availabilityevent')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='availabilityevent',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitor.offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='monitor.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='monitor.store'),
        ),
        migrations.CreateModel(
            name='WatchTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('mode', models.CharField(choices=[('product_page', 'Product page'), ('search_page', 'Search page'), ('category_page', 'Category page')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('poll_interval_seconds', models.PositiveIntegerField(default=300)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('next_check_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parser_config', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watch_targets', to='monitor.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_targets', to='monitor.store')),
            ],
            options={
                'ordering': ['next_check_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='watch_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='monitor.watchtarget'),
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], default='queued', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('items_found', models.PositiveIntegerField(default=0)),
                ('parser_name', models.CharField(blank=True, max_length=255)),
                ('debug_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_runs', to='monitor.store')),
                ('watch_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_runs', to='monitor.watchtarget')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(fields=('store', 'watch_target', 'url'), name='unique_offer_per_watch_target_url'),
        ),
    ]
