# Generated by Django 6.0.6 on 2026-06-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='parser_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('generic_woocommerce', 'Generic WooCommerce')], default='generic', max_length=50),
        ),
    ]
