# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_alter_store_parser_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="parser_type",
            field=models.CharField(
                choices=[
                    ("generic", "Generic"),
                    ("generic_woocommerce", "Generic WooCommerce"),
                    (
                        "cloudflare_api_replay_woocommerce",
                        "Cloudflare API replay WooCommerce",
                    ),
                ],
                default="generic",
                max_length=50,
            ),
        ),
    ]
